spring.application.name=auth-service
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:6000/auth-service
spring.datasource.username=alexa
spring.datasource.password=auth-service
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.kafka.bootstrap-servers=localhost:9092
jwt.secret=your-secret-key-for-jwt-tokens-256-bit-min-must-be-long
jwt.expiration=86400000
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

resend.api.key=${RESEND_API_KEY}
resend.from.email=onboarding@resend.dev